In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from keras.utils.np_utils import to_categorical

Using TensorFlow backend.


In [2]:
features = pd.read_pickle("loaded_data/features.pkl")

In [3]:
target = pd.read_pickle("loaded_data/target.pkl")

In [4]:
features.head()

lesion_id      image_id   dx dx_type   age   sex localization  \
0  HAM_0000118  ISIC_0027419  bkl   histo  80.0  male        scalp   
1  HAM_0000118  ISIC_0025030  bkl   histo  80.0  male        scalp   
2  HAM_0002730  ISIC_0026769  bkl   histo  80.0  male        scalp   
3  HAM_0002730  ISIC_0025661  bkl   histo  80.0  male        scalp   
4  HAM_0001466  ISIC_0031633  bkl   histo  75.0  male          ear   

                                      path                       cell_type  \
0  HAM10000_images_part_1\ISIC_0027419.jpg  Benign keratosis-like lesions    
1  HAM10000_images_part_1\ISIC_0025030.jpg  Benign keratosis-like lesions    
2  HAM10000_images_part_1\ISIC_0026769.jpg  Benign keratosis-like lesions    
3  HAM10000_images_part_1\ISIC_0025661.jpg  Benign keratosis-like lesions    
4  HAM10000_images_part_2\ISIC_0031633.jpg  Benign keratosis-like lesions    

                                               image  
0  [[[190, 153, 194], [192, 154, 196], [191, 153,...  
1  [[[23, 13, 22], [24, 14, 24], [25, 14, 28], [3...  
2  [[[185, 127, 137], [189, 133, 147], [194, 136,...  
3  [[[24, 11, 17], [26, 13, 22], [38, 21, 32], [5...  
4  [[[134, 90, 113], [147, 102, 125], [159, 115, ...

In [5]:
target.head()

0    2
1    2
2    2
3    2
4    2
Name: cell_type_idx, dtype: int8

In [4]:
x_train_o, x_test_o, y_train_o, y_test_o = train_test_split(features, target, test_size=0.20,random_state=1234)

In [6]:
x_train_o.head(15)

lesion_id      image_id   dx    dx_type   age     sex  \
8442  HAM_0006451  ISIC_0032274   nv      histo  50.0  female   
2908  HAM_0003941  ISIC_0029745  bcc      histo  35.0    male   
8909  HAM_0001989  ISIC_0030251   nv      histo  65.0    male   
58    HAM_0000700  ISIC_0028052  bkl      histo  60.0    male   
2960  HAM_0000868  ISIC_0032316  bcc      histo  65.0    male   
6689  HAM_0004886  ISIC_0029214   nv      histo  45.0  female   
8468  HAM_0006258  ISIC_0028484   nv      histo  10.0  female   
2810  HAM_0006386  ISIC_0029035  bcc      histo  70.0    male   
1733  HAM_0002732  ISIC_0033874  mel      histo  65.0    male   
4347  HAM_0001653  ISIC_0027895   nv  follow_up  55.0  female   
7319  HAM_0004574  ISIC_0032671   nv      histo  70.0  female   
11    HAM_0004234  ISIC_0029396  bkl      histo  85.0  female   
1160  HAM_0002450  ISIC_0024396   df  consensus  65.0  female   
6442  HAM_0000333  ISIC_0029098   nv  follow_up  40.0    male   
8667  HAM_0006154  ISIC_0030082   nv      histo  20.0    male   

         localization                                     path  \
8442             back  HAM10000_images_part_2\ISIC_0032274.jpg   
2908             face  HAM10000_images_part_2\ISIC_0029745.jpg   
8909  lower extremity  HAM10000_images_part_2\ISIC_0030251.jpg   
58               face  HAM10000_images_part_1\ISIC_0028052.jpg   
2960             face  HAM10000_images_part_2\ISIC_0032316.jpg   
6689             back  HAM10000_images_part_1\ISIC_0029214.jpg   
8468  upper extremity  HAM10000_images_part_1\ISIC_0028484.jpg   
2810             face  HAM10000_images_part_1\ISIC_0029035.jpg   
1733            chest  HAM10000_images_part_2\ISIC_0033874.jpg   
4347  lower extremity  HAM10000_images_part_1\ISIC_0027895.jpg   
7319             back  HAM10000_images_part_2\ISIC_0032671.jpg   
11              chest  HAM10000_images_part_2\ISIC_0029396.jpg   
1160  lower extremity  HAM10000_images_part_1\ISIC_0024396.jpg   
6442             hand  HAM10000_images_part_1\ISIC_0029098.jpg   
8667  lower extremity  HAM10000_images_part_2\ISIC_0030082.jpg   

                           cell_type  \
8442                Melanocytic nevi   
2908            Basal cell carcinoma   
8909                Melanocytic nevi   
58    Benign keratosis-like lesions    
2960            Basal cell carcinoma   
6689                Melanocytic nevi   
8468                Melanocytic nevi   
2810            Basal cell carcinoma   
1733                        Melanoma   
4347                Melanocytic nevi   
7319                Melanocytic nevi   
11    Benign keratosis-like lesions    
1160                  Dermatofibroma   
6442                Melanocytic nevi   
8667                Melanocytic nevi   

                                                  image  
8442  [[[156, 114, 126], [160, 120, 131], [164, 125,...  
2908  [[[202, 147, 163], [201, 144, 162], [200, 143,...  
8909  [[[182, 162, 157], [186, 166, 160], [188, 168,...  
58    [[[30, 16, 23], [33, 20, 27], [43, 28, 38], [5...  
2960  [[[155, 101, 97], [155, 102, 98], [159, 109, 1...  
6689  [[[193, 172, 192], [195, 175, 192], [197, 177,...  
8468  [[[212, 174, 166], [212, 175, 166], [216, 180,...  
2810  [[[146, 110, 97], [152, 117, 108], [154, 119, ...  
1733  [[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], ...  
4347  [[[214, 122, 149], [218, 125, 152], [216, 125,...  
7319  [[[164, 152, 164], [169, 163, 176], [169, 165,...  
11    [[[152, 122, 123], [153, 123, 123], [158, 129,...  
1160  [[[188, 150, 156], [190, 155, 163], [190, 152,...  
6442  [[[235, 145, 172], [235, 147, 174], [237, 149,...  
8667  [[[233, 207, 205], [232, 208, 203], [233, 209,...

In [7]:
x_test_o.head(15)

lesion_id      image_id    dx    dx_type   age     sex  \
6066  HAM_0000628  ISIC_0024567    nv  follow_up  35.0  female   
7912  HAM_0004226  ISIC_0032760    nv      histo  25.0  female   
7903  HAM_0002015  ISIC_0034035    nv      histo  30.0  female   
7126  HAM_0001651  ISIC_0033251    nv      histo  45.0    male   
692   HAM_0003206  ISIC_0025199   bkl      histo  60.0  female   
7358  HAM_0002016  ISIC_0032805    nv      histo  70.0    male   
7746  HAM_0003801  ISIC_0033978    nv      histo  45.0    male   
8454  HAM_0005016  ISIC_0027045    nv      histo  60.0    male   
3487  HAM_0002013  ISIC_0026168    nv  follow_up  35.0    male   
401   HAM_0004945  ISIC_0030258   bkl      histo  85.0    male   
7553  HAM_0006042  ISIC_0033983    nv      histo  50.0    male   
2437  HAM_0004409  ISIC_0027888  vasc  consensus  40.0    male   
3084  HAM_0000750  ISIC_0027974    nv  follow_up  45.0    male   
9435  HAM_0001916  ISIC_0033537    nv  consensus  20.0    male   
1510  HAM_0007343  ISIC_0033946   mel      histo  70.0    male   

         localization                                     path  \
6066  lower extremity  HAM10000_images_part_1\ISIC_0024567.jpg   
7912            trunk  HAM10000_images_part_2\ISIC_0032760.jpg   
7903  lower extremity  HAM10000_images_part_2\ISIC_0034035.jpg   
7126             back  HAM10000_images_part_2\ISIC_0033251.jpg   
692   lower extremity  HAM10000_images_part_1\ISIC_0025199.jpg   
7358  lower extremity  HAM10000_images_part_2\ISIC_0032805.jpg   
7746             face  HAM10000_images_part_2\ISIC_0033978.jpg   
8454             back  HAM10000_images_part_1\ISIC_0027045.jpg   
3487          abdomen  HAM10000_images_part_1\ISIC_0026168.jpg   
401              back  HAM10000_images_part_2\ISIC_0030258.jpg   
7553          abdomen  HAM10000_images_part_2\ISIC_0033983.jpg   
2437            trunk  HAM10000_images_part_1\ISIC_0027888.jpg   
3084  lower extremity  HAM10000_images_part_1\ISIC_0027974.jpg   
9435             back  HAM10000_images_part_2\ISIC_0033537.jpg   
1510            chest  HAM10000_images_part_2\ISIC_0033946.jpg   

                           cell_type  \
6066                Melanocytic nevi   
7912                Melanocytic nevi   
7903                Melanocytic nevi   
7126                Melanocytic nevi   
692   Benign keratosis-like lesions    
7358                Melanocytic nevi   
7746                Melanocytic nevi   
8454                Melanocytic nevi   
3487                Melanocytic nevi   
401   Benign keratosis-like lesions    
7553                Melanocytic nevi   
2437                Vascular lesions   
3084                Melanocytic nevi   
9435                Melanocytic nevi   
1510                        Melanoma   

                                                  image  
6066  [[[212, 118, 144], [210, 117, 139], [212, 120,...  
7912  [[[32, 25, 33], [44, 34, 45], [61, 49, 63], [7...  
7903  [[[148, 136, 158], [152, 141, 165], [155, 146,...  
7126  [[[101, 87, 99], [111, 99, 112], [116, 108, 12...  
692   [[[188, 166, 174], [188, 170, 179], [188, 166,...  
7358  [[[111, 75, 107], [114, 77, 108], [121, 86, 11...  
7746  [[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], ...  
8454  [[[167, 123, 124], [163, 114, 111], [161, 110,...  
3487  [[[226, 153, 161], [229, 153, 162], [229, 152,...  
401   [[[174, 161, 166], [174, 162, 167], [173, 160,...  
7553  [[[194, 169, 184], [192, 170, 182], [193, 171,...  
2437  [[[199, 145, 146], [199, 143, 145], [199, 143,...  
3084  [[[233, 156, 175], [234, 159, 177], [231, 152,...  
9435  [[[148, 113, 133], [153, 116, 137], [156, 118,...  
1510  [[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], ...

In [8]:
y_train_o.head(15)

8442    4
2908    1
8909    4
58      2
2960    1
6689    4
8468    4
2810    1
1733    5
4347    4
7319    4
11      2
1160    3
6442    4
8667    4
Name: cell_type_idx, dtype: int8

In [9]:
y_test_o.head(15)

6066    4
7912    4
7903    4
7126    4
692     2
7358    4
7746    4
8454    4
3487    4
401     2
7553    4
2437    6
3084    4
9435    4
1510    5
Name: cell_type_idx, dtype: int8

In [8]:
x_train = np.asarray(x_train_o['image'].tolist())
x_test = np.asarray(x_test_o['image'].tolist())

In [9]:
x_train_mean = np.mean(x_train)
x_train_std = np.std(x_train)

print(x_train_mean)
print(x_train_std)

159.88411714650246
46.45448942251337


In [17]:
x_test_mean = np.mean(x_test)
x_test_std = np.std(x_test)

In [18]:
x_train = (x_train - x_train_mean)/x_train_std
x_test = (x_test - x_test_mean)/x_test_std

In [21]:
y_train = to_categorical(y_train_o, num_classes = 7)
y_test = to_categorical(y_test_o, num_classes = 7)

In [23]:
print(x_train)

[[[[-8.36112332e-02 -9.87721913e-01 -7.29404576e-01]
   [ 2.49454584e-03 -8.58563244e-01 -6.21772352e-01]
   [ 8.86003248e-02 -7.50931020e-01 -5.35666573e-01]
   ...
   [-4.05583437e-02 -1.35367147e+00 -1.35367147e+00]
   [-1.69717012e-01 -1.50435659e+00 -1.54740948e+00]
   [-1.91243457e-01 -1.54740948e+00 -1.65504170e+00]]

  [[-1.90318989e-02 -9.23142578e-01 -6.86351686e-01]
   [ 6.70738801e-02 -7.72457465e-01 -5.57193018e-01]
   [ 1.53179659e-01 -6.64825241e-01 -4.92613683e-01]
   ...
   [ 4.55474353e-02 -1.24603925e+00 -1.31061858e+00]
   [-8.36112332e-02 -1.37519792e+00 -1.46130370e+00]
   [-1.05137678e-01 -1.39672436e+00 -1.46130370e+00]]

  [[ 2.40209906e-02 -8.37036799e-01 -6.43298797e-01]
   [ 1.10126770e-01 -6.86351686e-01 -5.35666573e-01]
   [ 1.96232549e-01 -6.00245907e-01 -4.49560794e-01]
   ...
   [ 2.40209906e-02 -1.28909214e+00 -1.39672436e+00]
   [ 2.40209906e-02 -1.31061858e+00 -1.35367147e+00]
   [ 2.49454584e-03 -1.28909214e+00 -1.31061858e+00]]

  ...

  [[ 2.17758

In [24]:
print(y_train)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


In [25]:
print(x_test)

[[[[ 1.13400853 -0.89837419 -0.33622578]
   [ 1.09076634 -0.91999528 -0.44433124]
   [ 1.13400853 -0.85513201 -0.40108906]
   ...
   [ 0.98266088 -1.02810075 -0.48757343]
   [ 1.00428197 -0.98485856 -0.44433124]
   [ 1.04752416 -0.96323747 -0.44433124]]

  [[ 1.02590307 -1.02810075 -0.53081561]
   [ 1.00428197 -1.04972184 -0.5740578 ]
   [ 1.11238744 -0.8767531  -0.42271015]
   ...
   [ 1.02590307 -0.96323747 -0.48757343]
   [ 1.02590307 -0.94161638 -0.44433124]
   [ 0.98266088 -0.98485856 -0.55243671]]

  [[ 1.04752416 -0.94161638 -0.46595234]
   [ 1.06914525 -0.96323747 -0.48757343]
   [ 1.04752416 -1.00647966 -0.46595234]
   ...
   [ 1.02590307 -0.94161638 -0.50919452]
   [ 1.02590307 -0.89837419 -0.48757343]
   [ 0.96103979 -1.00647966 -0.61729999]]

  ...

  [[ 0.6367234  -1.11458512 -0.85513201]
   [ 0.67996558 -1.04972184 -0.79026873]
   [ 0.6151023  -1.30917495 -0.94161638]
   ...
   [ 0.78807105 -0.89837419 -0.68216326]
   [ 0.74482886 -0.89837419 -0.74702654]
   [ 0.65834449 

In [26]:
print(y_test)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


In [10]:
x_train, x_validate, y_train, y_validate = train_test_split(x_train, y_train, test_size = 0.1, random_state = 2)

NameError: name 'x_train' is not defined

In [28]:
x_train = x_train.reshape(x_train.shape[0], *(75, 100, 3))
x_test = x_test.reshape(x_test.shape[0], *(75, 100, 3))
x_validate = x_validate.reshape(x_validate.shape[0], *(75, 100, 3))

In [33]:
np.save("loaded_data/x_train.npy", x_train,  allow_pickle=True)
np.save("loaded_data/y_train.npy", y_train,  allow_pickle=True)

In [34]:
np.save("loaded_data/x_validate.npy", x_validate,  allow_pickle=True)
np.save("loaded_data/y_validate.npy", y_validate,  allow_pickle=True)

In [35]:
np.save("loaded_data/x_test.npy", x_test,  allow_pickle=True)
np.save("loaded_data/y_test.npy", y_test,  allow_pickle=True)

In [36]:
x_train_o.head()

lesion_id      image_id   dx dx_type   age     sex     localization  \
8442  HAM_0006451  ISIC_0032274   nv   histo  50.0  female             back   
2908  HAM_0003941  ISIC_0029745  bcc   histo  35.0    male             face   
8909  HAM_0001989  ISIC_0030251   nv   histo  65.0    male  lower extremity   
58    HAM_0000700  ISIC_0028052  bkl   histo  60.0    male             face   
2960  HAM_0000868  ISIC_0032316  bcc   histo  65.0    male             face   

                                         path                       cell_type  \
8442  HAM10000_images_part_2\ISIC_0032274.jpg                Melanocytic nevi   
2908  HAM10000_images_part_2\ISIC_0029745.jpg            Basal cell carcinoma   
8909  HAM10000_images_part_2\ISIC_0030251.jpg                Melanocytic nevi   
58    HAM10000_images_part_1\ISIC_0028052.jpg  Benign keratosis-like lesions    
2960  HAM10000_images_part_2\ISIC_0032316.jpg            Basal cell carcinoma   

                                                  image  
8442  [[[156, 114, 126], [160, 120, 131], [164, 125,...  
2908  [[[202, 147, 163], [201, 144, 162], [200, 143,...  
8909  [[[182, 162, 157], [186, 166, 160], [188, 168,...  
58    [[[30, 16, 23], [33, 20, 27], [43, 28, 38], [5...  
2960  [[[155, 101, 97], [155, 102, 98], [159, 109, 1...

In [37]:
x_train_o.to_pickle("loaded_data/x_train_o.pkl")
y_train_o.to_pickle("loaded_data/y_train_o.pkl")
x_test_o.to_pickle("loaded_data/x_test_o.pkl")
y_test_o.to_pickle("loaded_data/y_test_o.pkl")